services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: senao_test
      POSTGRES_USER: shaun
      POSTGRES_PASSWORD: shaunchen1234

  web:
    image: motestw64631/account-manager
    ports:
      - "8087:8087"
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"